# Generated by Django 3.2 on 2022-09-19 16:02

from django.db import migrations


def forwards_func(apps, schema_editor):
    Courses = apps.get_model("mainapp", "Courses")
    Courses.objects.create(
        name='Web Python',
        description='Course is about how to became a Python backend developer',
        cost=300
    )
    Courses.objects.create(
        name='Web Golang',
        description='Course is about how to became a Golang backend developer',
        cost=300
    )
    Courses.objects.create(
        name='Web JavaScript',
        description='Course is about how to became a JavaScript backend developer',
        cost=300
    )
    Courses.objects.create(
        name='Web PHP',
        description='Course is about how to became a PHP backend developer',
        cost=250
    )
    Courses.objects.create(
        name='Web Java',
        description='Course is about how to became a Java backend developer',
        cost=100
    )


def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0002_news_migration'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
