# Generated by Django 3.2 on 2022-09-19 16:03

from django.db import migrations


def forwards_func(apps, schema_editor):
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    Course = apps.get_model("mainapp", "Courses")

    CourseTeachers.objects.create(
        name_first='Iakov',
        name_second='Saiko',
        day_birth="1988-02-04",
    )
    CourseTeachers.objects.create(
        name_first='Sax',
        name_second='Alex',
        day_birth="1988-02-04",
    )
    CourseTeachers.objects.create(
        name_first='Rek',
        name_second='Zukov',
        day_birth="1988-02-04",
    )

    CourseTeachers.objects.get(pk=1).course.add(1)
    CourseTeachers.objects.get(pk=1).course.add(2,5)
    CourseTeachers.objects.get(pk=1).course.add(3)



def reverse_func(apps, schema_editor):
    # Get model
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    # Delete objects
    CourseTeachers.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0004_lessons_migration'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
