# Generated by Django 3.2 on 2022-09-19 16:03

from django.db import migrations


def forwards_func(apps, schema_editor):
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    Course = apps.get_model("mainapp", "Courses")

    CourseTeachers.objects.create(
        course=Course.objects.get(id=1),
        name_first='Iakov',
        name_second='Saiko',
    )
    CourseTeachers.objects.create(
        course=Course.objects.get(id=1),
        name_first='Sax',
        name_second='Alex',
    )
    CourseTeachers.objects.create(
        course=Course.objects.get(id=1),
        name_first='Rek',
        name_second='Zukov',
    )


def reverse_func(apps, schema_editor):
    # Get model
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    # Delete objects
    CourseTeachers.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0004_lessons_migration'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
