# Generated by Django 3.2 on 2022-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_course_teachers_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteachers',
            name='day_birth',
            field=models.DateField(auto_now_add=True, verbose_name='Birth date'),
        ),
    ]
